openapi: 3.0.0
info:
  title: EduSoho接口
  description: EduSoho接口，随版本动态变化
  version: default
paths:
  '/course/{courseId}/reviews':
    get:
      operationId: ba17b899ada47f1ec036809f24c1fc85
      responses:
        '200':
          description: '获取课程的评价 '
  '/api/course/{courseId}/notes/{noteId}':
    get:
      tags:
        - course
      summary: 课程单个笔记获取接口
      responses:
        '200':
          description: 单条笔记
          content:
            application/vnd.edusoho.v2+json:
              schema:
                $ref: '@/components/schemas/course.note'
  /api/settings/signSecurity:
    get:
      tags:
        - setting
      summary: 获取接口加密设置
      responses:
        '200':
          description: 加密设置
          content:
            application/vnd.edusoho.v2+json:
              schema:
                $ref: '#/components/schemas/setting.signSecurity'
  /api/settings/locale:
    get:
      tags:
        - setting
      summary: 获取系统语言设置
      responses:
        '200':
          description: 语言设置
          content:
            application/vnd.edusoho.v2+json:
              schema:
                $ref: '#/components/schemas/setting.locale'
  /api/settings/ugc:
    get:
      tags:
        - setting
      summary: 获取UGC设置
      responses:
        '200':
          description: 全部UGC设置
          content:
            application/vnd.edusoho.v2+json:
              schema:
                $ref: '#/components/schemas/setting.ugc'
  /api/settings/ugc_review:
    get:
      tags:
        - setting
      summary: 获取评价UGC设置
      responses:
        '200':
          description: 评价UGC设置
          content:
            application/vnd.edusoho.v2+json:
              schema:
                $ref: '#/components/schemas/setting.ugc_review'
  /api/settings/ugc_note:
    get:
      tags:
        - setting
      summary: 获取笔记UGC设置
      responses:
        '200':
          description: 笔记UGC设置
          content:
            application/vnd.edusoho.v2+json:
              schema:
                $ref: '#/components/schemas/setting.ugc_note'
  /api/settings/ugc_thread:
    get:
      tags:
        - setting
      summary: 获取话题问答UGC设置
      responses:
        '200':
          description: 话题问答UGC设置
          content:
            application/vnd.edusoho.v2+json:
              schema:
                $ref: '#/components/schemas/setting.ugc_thread'
  /api/settings/ugc_private_message:
    get:
      tags:
        - setting
      summary: 获取私信UGC设置
      responses:
        '200':
          description: 私信UGC设置
          content:
            application/vnd.edusoho.v2+json:
              schema:
                $ref: '#/components/schemas/setting.ugc_private_message'
  /api/settings/task_learning_config:
    get:
      tags:
        - setting
      summary: 任务学习设置
      responses:
        '200':
          description: 任务学习设置
          content:
            application/vnd.edusoho.v2+json:
              schema:
                $ref: '#/components/schemas/setting.task_learning_config'
components:
  schemas:
    course.note:
      title: course.note
      description: 课程笔记
      properties:
        '':
          $ref: '#/components/schemas/user.simple'
      type: object
    setting.signSecurity:
      title: setting.signSecurity
      description: 接口安全加密设置信息
      properties:
        level:
          title: level
          description: 安全校验等级：close（不校验）、optional（佛系校验）、open（强制校验）
          type: string
          default: close
          enum:
            - close
            - optional
            - open
        clients:
          title: clients
          description: 需要校验的设备列表：包含ios、android、miniprogram、other
          type: array
          items:
            type: string
            enum:
              - ios
              - android
              - miniprogram
              - other
          default: null
      type: object
    setting.locale:
      title: setting.locale
      description: 语言信息
      properties:
        locale:
          title: locale
          description: '语言：en,zh_CN'
          type: string
          default: zh_CN
          enum:
            - en
            - zh_CN
      type: object
    setting.ugc_review:
      title: setting.ugc_review
      description: 评价UGC设定
      properties:
        enable:
          title: enable
          description: 评价总开关
          type: integer
          default: 1
      type: object
    setting.ugc_note:
      title: setting.ugc_note
      description: 笔记UGC设定
      properties:
        enable:
          title: enable
          description: 笔记总开关
          type: integer
          default: 1
      type: object
    setting.ugc_thread:
      title: setting.ugc_thread
      description: 话题讨论UGC设定
      properties:
        enable:
          title: enable
          description: 话题讨论总开关
          type: integer
          default: 1
      type: object
    setting.ugc_private_message:
      title: setting.ugc_private_message
      description: 私信UGC设定
      properties:
        enable:
          title: enable
          description: 私信总开关
          type: integer
          default: 1
      type: object
    setting.ugc:
      title: setting.ugc
      description: 全局UGC设定
      properties:
        ugc_review:
          $ref: '#/components/schemas/setting.ugc_review'
        ugc_note:
          $ref: '#/components/schemas/setting.ugc_note'
        ugc_thread:
          $ref: '#/components/schemas/setting.ugc_thread'
        ugc_private_message:
          $ref: '#/components/schemas/setting.ugc_private_message'
      type: object
    setting.task_learning_config:
      title: setting.task_learning_config
      description: 课程任务学习配置
      properties:
        non_focus_learning_video_play_rule:
          description: '非专注学习规则,auto_pause:自动暂停、no_action:无操作'
          type: string
          default: no_action
          enum:
            - auto_pause
            - no_action
        media_play_continuously:
          description: 音视频连续播放
          type: string
          default: 'off'
          enum:
            - 'on'
            - 'off'
        multiple_learn:
          description: 多开学习
          properties:
            multiple_learn_enable:
              description: 是否多开学习
              type: string
              default: 'off'
              enum:
                - 'on'
                - 'off'
            multiple_learn_kick_mode:
              description: 多开学习模式，kick_previous：踢掉上一个播放、reject_current：拒绝本次播放
              type: string
              default: kick_previous
              enum:
                - kick_previous
                - reject_current
          type: object
      type: object
    user.simple:
      title: user.simple
      description: Simple用户对象
      properties:
        id:
          description: 用户ID
          type: integer
      type: object
tags:
  -
    name: course
    description: 课程接口集合
  -
    name: setting
    description: 系统设置接口集合
