openapi: 3.0.0
info:
  title: EduSoho接口
  description: EduSoho接口，随版本动态变化
  version: default
paths:
  '/course/{courseId}/reviews':
    get:
      operationId: ba17b899ada47f1ec036809f24c1fc85
      responses:
        '200':
          description: '获取课程的评价 '
  /api/settings/signSecurity:
    get:
      tags:
        - setting
      operationId: 8ed9f8d52a1a77b3fca95af0a358f86e
      responses:
        '200':
          description: 接口加密设置
          content:
            application/vnd.edusoho.v2+json:
              schema:
                $ref: '#/components/schemas/signSecurity'
  /api/settings/locale:
    get:
      tags:
        - setting
      operationId: da6717a0a0755cd98fdc224128d9ffe5
      responses:
        '200':
          description: 获取语言设置
          content:
            application/vnd.edusoho.v2+json:
              schema:
                $ref: '#/components/schemas/locale'
components:
  schemas:
    signSecurity:
      title: signSecurity
      description: 接口安全加密设置信息
      properties:
        level:
          title: level
          description: 安全校验等级：close（不校验）、optional（佛系校验）、open（强制校验）
          type: string
          default: close
          enum:
            - close
            - optional
            - open
        clients:
          title: clients
          description: 需要校验的设备列表：包含ios、android、miniprogram、other
          type: array
          items:
            type: string
            enum:
              - ios
              - android
              - miniprogram
              - other
          default: null
      type: object
    locale:
      title: locale
      description: 语言信息
      properties:
        locale:
          title: locale
          description: '语言：en,zh-CN'
          type: string
          default: zh_CN
          enum:
            - en
            - zh_CN
      type: object
tags:
  -
    name: setting
    description: 系统设置接口集合
